"use client";
import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";

// export const metadata = {
//     title: "House Of GOT",
//     description:
//         "A full stack application using Firebase and Next.js by integrating authentication and interacting with our database. Generated by Next.js",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head />
            <body>
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
}
